### ISSUE TITLE
Can't create request on Android

### ISSUE THREAD

**Issue by Luigifan** [jkovacs/lastfm-java#3]
For whatever reason, I'm unable to make any requests on Android. Logcat only shows that the request is being opened, but nothing else.

Upon importing the source into Android studio, I can trace it back as far as into the _openPostConnection_ method. The part where the urlConnection's OutputStream is passed into the outputStream variable is never called, and stops after "urlConnection.setDoOutput(true);". However, if I set a System.out after urlConnection.setDoOutput(true), this is called. I am unsure what is happening.

I came across this Stackoverflow question: http://stackoverflow.com/questions/8438415/last-fm-api-call-from-android-application
And tried setting cache to null as the answer suggested, but this had no effect on anything. 

My code is simplistic enough code that doesn't require authentication of the user, just getting their top tracks for the week (Android port of my lastfm-collage-generator repository). Any idea as to what on earth could be going on? Any possible solutions?

Thanks

**Comment by jkovacs** [comment]
Can you push your android port to github so I can take a look to troubleshoot this?

In any case, can you make sure this is not caused by the recent Last.fm site update (see [here](https://getsatisfaction.com/lastfm/topics/web-services-also-affected-by-new-site-launch)), e.g. by trying if some other API methods work or not?

**Comment by Riddim** [comment]
When I try to `User.getWeeklyArtistChart(user, 10, key);` on android this happens:
```
Caused by: de.umass.lastfm.CallException: Caching/Reloading failed
at de.umass.lastfm.Caller.call(Caller.java:246)
at de.umass.lastfm.Caller.call(Caller.java:189)
at de.umass.lastfm.Chart.getChart(Chart.java:103)
at de.umass.lastfm.Chart.getChart(Chart.java:80)
at de.umass.lastfm.User.getWeeklyArtistChart(User.java:244)
at de.umass.lastfm.User.getWeeklyArtistChart(User.java:240)
```

**Comment by nrmnrm** [comment]
Original issue is not an issue with this library. Problem is that Android does not allow network operations on UI thread. You have to move calls to the library into an asynctask.
